### ISSUE TITLE
Value <!DOCTYPE of type java.lang.String cannot be converted to JSONObject

### ISSUE THREAD

**Issue by joshuajennysibbu** [orangepreneur/payumoneySDK#2]
I am getting this issue `Value <!DOCTYPE of type java.lang.String cannot be converted to JSONObject` please help me fix this. I just copy your example code.

**Comment by withmukeshjoshi** [comment]
can you share how to replicate the error?

**Comment by joshuajennysibbu** [comment]
I just use your example code. When I click to make payment button it was navigating to the payment screen. After 1 second it was navigating back. and I get this error  `Value <!DOCTYPE of type java.lang.String cannot be converted to JSONObject`.

**Comment by gomcodoctor** [comment]
same issue here

**Comment by withmukeshjoshi** [comment]
may I know the flutter/dart/Java/Gradle versions you are using... also what Android SDK you are targeting

**Comment by gomcodoctor** [comment]
Flutter 2.10.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 097d3313d8 (7 weeks ago) • 2022-02-18 19:33:08 -0600
Engine • revision a83ed0e5e3
Tools • Dart 2.16.1 • DevTools 2.9.2

minSdkVersion 21

**Comment by akashkoffeekodes** [comment]
same problem i am also faceing

**Comment by withmukeshjoshi** [comment]
Tested the application, It is working fine. May I know more details maybe an example app with the code?

**Comment by shreyasSarve** [comment]
hey can some one tell me  the solution i am facing same issue
